# Generated by Django 4.0.4 on 2022-05-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('form_cadence', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('one_step', models.CharField(max_length=20)),
                ('sparring', models.CharField(max_length=20)),
                ('ecas', models.CharField(max_length=20)),
                ('boards', models.CharField(max_length=20)),
                ('results', models.CharField(max_length=20)),
                ('exam_author', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=250)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
