# Generated by Django 4.0.4 on 2022-06-07 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_primary', models.EmailField(max_length=50)),
                ('email_secondary', models.EmailField(blank=True, max_length=50)),
                ('primary_phone_number',
                 phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('secondary_phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('medical_info', models.CharField(max_length=100)),
                ('is_parent', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('dual_parent_student', models.BooleanField(default=False)),
                ('age', models.IntegerField()),
                ('male_gender', models.BooleanField(default=False)),
                ('female_gender', models.BooleanField(default=False)),
                ('guardian', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=100)),
                ('instructor', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
