# Generated by Django 4.0.4 on 2022-06-02 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('rank', models.CharField(
                    choices=[('BLANK', 'N/A'), ('CUB_WHITE', 'Cub_White'), ('CUB_YELLOW', 'Cub_Yellow'),
                             ('CUB_GREEN', 'Cub_Green'), ('CUB_BLUE', 'Cub_Blue'), ('CUB_BROWN', 'Cub_Brown'),
                             ('CUB_RED', 'Cub_Red'), ('CUB_BLACK', 'Cub_Black'), ('WHITE', 'White'),
                             ('YELLOW', 'Yellow'), ('GREEN_1', 'Green_1'), ('GREEN_2', 'Green_2'),
                             ('GREEN_3', 'Green_3'), ('BLUE_1', 'Blue_1'), ('BLUE_2', 'Blue_2'), ('BLUE_3', 'Blue_3'),
                             ('BROWN_1', 'Brown_1'), ('BROWN_2', 'Brown_2'), ('BROWN', 'Brown_3'), ('RED_1', 'Red_1'),
                             ('RED_2', 'Red_2'), ('RED_3', 'Red_3'), ('PROBATIONARY_BLACK', 'Probationary_Black'),
                             ('BLACK_1ST_1', 'Black_1ST_1'), ('BLACK_1ST_2', 'Black_1ST_2'),
                             ('BLACK_1ST_3', 'Black_1ST_3'), ('BLACK_2ND_1', 'Black_2ND_1'),
                             ('BLACK_2ND_2', 'Black_2ND_2'), ('BLACK_2ND_3', 'Black_2ND_3'),
                             ('BLACK_3RD_1', 'Black_3RD_1'), ('BLACK_3RD_2', 'Black_3RD_2'),
                             ('BLACK_3RD_3', 'Black_3RD_3'), ('BLACK_4TH_1', 'Black_4TH_1'),
                             ('BLACK_4TH_2', 'Black_4TH_2'), ('BLACK_4TH_3', 'Black_4TH_3'),
                             ('SR_1ST_DEGREE', 'Sr_1st_Degree'), ('SR_2ND_DEGREE', 'Sr_2nd_Degree'),
                             ('SR_3RD_DEGREE', 'Sr_3rd_Degree'), ('SR_4TH_DEGREE', 'Sr_4th_Degree')], max_length=200)),
                ('tkd_program', models.CharField(
                    choices=[('BLANK', 'N/A'), ('TIGER CUB', 'Tiger Cub'), ('JR', 'Jr'), ('YOUTH', 'Youth'),
                             ('ADULT', 'Adult')], max_length=200)),
                ('xp_program', models.CharField(
                    choices=[('BLANK', 'N/A'), ('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'),
                             ('ADVANCED', 'Advanced')], max_length=100)),
                ('sc_program', models.CharField(choices=[('BLANK', 'N/A'), ('WHITE', 'White'), ('YELLOW', 'Yellow')],
                                                max_length=100)),
                ('instructor', models.BooleanField()),
                ('member',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True)),
                ('exam_title', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=50)),
                ('form_cadence', models.BooleanField(default=False)),
                ('contact', models.BooleanField(default=False)),
                ('one_step', models.BooleanField(default=False)),
                ('sparring', models.BooleanField(default=False)),
                ('ecas', models.BooleanField(default=False)),
                ('boards', models.BooleanField(default=False)),
                ('results', models.CharField(blank=True, max_length=20)),
                ('exam_author', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
