# Generated by Django 4.0.4 on 2022-06-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('member', '0001_initial'),
        ('student', '0002_alter_exam_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
            preserve_default=False,
        ),
    ]
